CREATE TABLE [dbo].[BankTransaction]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	[TypeId] INT NULL,
    [TransactionId] VARCHAR(50) NULL, 
    [UserName] VARCHAR(50) NULL, 
    [Password] VARCHAR(50) NULL, 
    [FromAccountName] VARCHAR(50) NULL, 
    [ToAccountName] VARCHAR(50) NULL, 
    [FromAccountNumber] VARCHAR(50) NULL, 
    [ToAccountNumber] VARCHAR(50) NULL,
	[Content] NVARCHAR(200) NULL, 
    [Amount] DECIMAL NULL, 
	[FromBankId] INT NULL, 
	[ToBankId] INT NULL, 
	[Captcha] VARCHAR(20) NULL, 
    [Otp] VARCHAR(20) NULL, 
    [OtpRef] VARCHAR(20) NULL, 
	[BankCharge] DECIMAL(8) NULL, 
    [Balance] DECIMAL NULL, 
	[LastPage] NVARCHAR(MAX) NULL,
	[CreatedTime] DATETIME NULL DEFAULT GETDATE(),
	[LastUpdatedTime] DATETIME NULL, 
	[CreatedByUserID] INT NOT NULL,
	[LastUpdatedByUserID] INT NOT NULL,
	CONSTRAINT FK_BankTransaction_User FOREIGN KEY([CreatedByUserID]) REFERENCES [dbo].[User]([Id]),
	CONSTRAINT FK_BankTransaction_User_1 FOREIGN KEY([LastUpdatedByUserID]) REFERENCES [dbo].[User]([Id]),
    CONSTRAINT FK_BankTransaction_TransactionType FOREIGN KEY ([TypeId]) REFERENCES TransactionType(Id),
    CONSTRAINT FK_BankTransaction_Bank FOREIGN KEY ([FromBankId]) REFERENCES Bank(Id),
    CONSTRAINT FK_BankTransaction_Bank_1 FOREIGN KEY ([ToBankId]) REFERENCES Bank(Id),
)
