CREATE TABLE [dbo].[Step]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[PreviousStepId] int NULL, 
	[CurrentStepId] int NOT NULL, 
	[NextStepId1] int NULL, 
	[NextStepId0] int NULL, 
	[InputTypeId] int NULL, 
	[StepTypeId] int NOT NULL, 
    [BankId] INT NOT NULL, 
    [Name] VARCHAR(100) NULL, 
	[Url] NVARCHAR(500) NULL, 
    [Params] NVARCHAR(500) NULL,
	[QueyStrings] NVARCHAR(500) NULL, 
    [Encoding] VARCHAR(50) NULL, 
    [Sign] VARCHAR(100) NULL,
	[Pattern] VARCHAR(100) NULL,
	[XPath] VARCHAR(100) NULL,
	[XPathAttribute] VARCHAR(20) NULL,
	IsConditionType BIT NULL DEFAULT 0,
	CONSTRAINT FK_Step_StepType FOREIGN KEY([StepTypeId]) REFERENCES StepType([Id]),
	CONSTRAINT FK_Step_Bank FOREIGN KEY([BankId]) REFERENCES Bank([Id]),
	CONSTRAINT FK_Step_InputType FOREIGN KEY([InputTypeId]) REFERENCES InputType([Id]),
)
