CREATE TABLE [dbo].[User]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [NAME] NVARCHAR(50) NOT NULL,
    [Password] NVARCHAR(50) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
	[Avatar] IMAGE NULL,
	[RoleId] INT NOT NULL,
	[Active] BIT NULL DEFAULT 1,
	[CreatedTime] DATETIME NULL DEFAULT GETDATE(),
	[LastUpdatedTime] DATETIME NULL,
	CONSTRAINT FK_User_Role FOREIGN KEY([RoleId]) REFERENCES UserRole([Id]),
)
