//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Razzil.DataAccess.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransaction
    {
        public int Id { get; set; }
        public string TransactionId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string FromAccountNumber { get; set; }
        public Nullable<int> FromBankId { get; set; }
        public string ToAccountNumber { get; set; }
        public Nullable<int> ToBankId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> BankCharge { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public string Otp { get; set; }
        public string OtpRef { get; set; }
        public string LastPage { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Bank Bank1 { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
