//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Razzil.DataAccess.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransaction
    {
        public int Id { get; set; }
        public string TransactionId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string FromAccountNumber { get; set; }
        public Nullable<int> FromBankId { get; set; }
        public string ToAccountNumber { get; set; }
        public Nullable<int> ToBankId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> BankCharge { get; set; }
        public string LastPage { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FromAccountName { get; set; }
        public string ToAccountName { get; set; }
        public string Content { get; set; }
        public string Captcha { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public int CreatedByUserID { get; set; }
        public int LastUpdatedByUserID { get; set; }
        public string OTP { get; set; }
        public string OTPRef { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Bank Bank1 { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual UserRole UserRole1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
