//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Razzil.DataAccess.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Captcha
    {
        public int Id { get; set; }
        public byte[] Image { get; set; }
        public string Result { get; set; }
        public Nullable<bool> Passed { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public int CreatedByUserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
