//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Razzil.DataAccess.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public int Id { get; set; }
        public Nullable<int> PreviousStepId { get; set; }
        public int CurrentStepId { get; set; }
        public Nullable<int> NextStepId1 { get; set; }
        public Nullable<int> NextStepId0 { get; set; }
        public int StepTypeId { get; set; }
        public int BankId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Params { get; set; }
        public string Encoding { get; set; }
        public string Sign { get; set; }
        public string Pattern { get; set; }
        public string XPath { get; set; }
        public string QueyStrings { get; set; }
        public string XPathAttribute { get; set; }
        public Nullable<bool> IsConditionType { get; set; }
        public Nullable<int> InputTypeId { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual StepType StepType { get; set; }
        public virtual InputType InputType { get; set; }
    }
}
